mqtt:
  broker: "ssl://broker.emqx.io:8883"
  client_id: "iot_heartbeat_service-"
  topic: "$share/heartbeat/iot-heartbeat"
  tls:
    ca_cert: "certs/broker.emqx.io-ca.crt"
  QOS: 1

database:
  host: "mgyesa3twa.m6cs99jzs9.tsdb.cloud.timescale.com"
  user: "tsdbadmin"
  password: "x2d85qp40hmir0qf"
  dbname: "tsdb"
  port: 38527
  sslmode: "require"
